export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const USER_ROUTE = '/user'
export const QUESTION_ROUTE = '/question'
export const PENDING_ROUTE = '/pending'
export const EDIT_ROUTE = '/edit'